@startuml
class SimpleCameraController {
    m_TargetCameraState : CameraState
    m_InterpolatingCameraState : CameraState
    + boost : float = 3.5f
    + positionLerpTime : float = 0.2f
    + mouseSensitivityCurve : AnimationCurve
    + rotationLerpTime : float = 0.01f
    + invertY : bool = false
    OnEnable() : void
    GetInputTranslationDirection() : Vector3
    Update() : void
}
class CameraState {
    + yaw : float
    + pitch : float
    + roll : float
    + x : float
    + y : float
    + z : float
    + SetFromTransform(t:Transform) : void
    + Translate(translation:Vector3) : void
    + LerpTowards(target:CameraState, positionLerpPct:float, rotationLerpPct:float) : void
    + UpdateTransform(t:Transform) : void
}
MonoBehaviour <|-- SimpleCameraController
SimpleCameraController +-- CameraState
@enduml
