@startuml
interface IVersionedMonoBehaviourInternal {
    UpgradeFromUnityThread() : void
}
abstract class VersionedMonoBehaviour {
    version : int = 0
    # <<virtual>> Awake() : void
    # <<virtual>> Reset() : void
    OnBeforeSerialize() : void
    OnAfterDeserialize() : void
    # <<virtual>> OnUpgradeSerializedData(version:int, unityThread:bool) : int
    UpgradeFromUnityThread() : void
}
MonoBehaviour <|-- VersionedMonoBehaviour
ISerializationCallbackReceiver <|-- VersionedMonoBehaviour
IVersionedMonoBehaviourInternal <|-- VersionedMonoBehaviour
@enduml
