@startuml
class SeekerEditor {
    {static} tagPenaltiesOpen : bool
    {static} scripts : List<Seeker>
    exactnessLabels : GUIContent[]
    graphLabels : string[]
    # <<override>> Inspector() : void
}
EditorBase <|-- SeekerEditor
@enduml
